# Usa Python 3.12 como imagen base
FROM python:3.12-slim

# Instala las dependencias del sistema necesarias para PyAudio y ffmpeg
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY . /app

# Crea el entorno virtual
RUN python -m venv /opt/venv

# Activa el entorno virtual e instala las dependencias
RUN /opt/venv/bin/pip install --upgrade pip
RUN /opt/venv/bin/pip install -r requirements.txt

# Configura el PATH para usar el entorno virtual de forma predeterminada
ENV PATH="/opt/venv/bin:$PATH"

# Expone el puerto en el que tu aplicación escucha (por ejemplo, 8000)
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["gunicorn", "--worker-class", "eventlet", "-w", "1", "-b", "0.0.0.0:8000", "app:app"]
